[tool.poetry]
name = "sensor"
version = "0.1.0"
description = "Temperature and humidity sensor abstraction"
authors = []
license = "GPL-3.0-only"
readme = "README.md"

[[tool.poetry.packages]]
include = "sensor"

[tool.poetry.dependencies]
python = ">=3.9"

[tool.poetry.group.dev.dependencies]
ruff = "0.1.5"
pytest = "7.3.1"
black = "^23.12.0"


[tool.poetry.group.grpc.dependencies]
grpcio-tools = "^1.60.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]
