name: CI
on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - uses: astral-sh/setup-uv@v6
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
        env:
          HUSKY: 0
      - run: npx nx format:check
      - run: npx nx affected -t sync
      - run: npx nx affected -t format,lint,typecheck
      - run: npx nx affected -t test
        env:
          BACKEND_CORS_ENABLED: 'False'
          BACKEND_CORS_ALLOW_ORIGINS: '[]'
          BACKEND_SENSOR_HOST: 'https://www.example.com/'
      - run: npx playwright install --with-deps
      - run: npx nx run rasptherm-e2e:e2e:ci
        env:
          BACKEND_CORS_ENABLED: 'True'
          BACKEND_CORS_ALLOW_ORIGINS: '["http://localhost:4300"]'
          BACKEND_SENSOR_HOST: 'localhost:5000'
          VITE_BACKEND_URL: 'http://localhost:8000'
